// components/footer/webfooter.vue
<template>
  <footer class="footer-container">
    <div class="footer-text">
      <span>© 2024-{{ currentYear }} Mooshieblob</span>
      <a
        id="ipv6"
        href="https://iplocation.io/ipv6-compatibility-checker?url=referer"
      >
        <img
          src="https://iplocation.io/images/ipv6-non-validated.svg"
          alt="ipv6 ready"
          title="ipv6 ready"
          style="border: 0; padding: 0"
          width="36"
          height="18"
        />
      </a>
    </div>
  </footer>
</template>

<script setup>
import "~/assets/css/output.css";

const currentYear = new Date().getFullYear();
</script>

<style scoped>
.footer-container {
  background-color: transparent;
  text-align: center;
  padding: 20px;
  text-shadow: 0 0 8px black;
  position: relative !important;
}
</style>

// components/footer/WebFooter.tsx
import type { JSX } from "preact/jsx-runtime";

export default function WebFooter(): JSX.Element {
    return (
        <footer class="footer-container">
            <div class="footer-text">
                <span>&copy; {new Date().getFullYear()} Mooshieblob</span>
                <a
                    id="ipv6"
                    href="https://iplocation.io/ipv6-compatibility-checker?url=referer"
                >
                    <img
                        src="https://iplocation.io/images/ipv6-non-validated.svg"
                        alt="ipv6 ready"
                        title="ipv6 ready"
                        style={{
                            border: 0,
                            padding: 0,
                            width: "36px",
                            height: "18px",
                            marginLeft: "10px",
                        }}
                    />
                </a>
            </div>
        </footer>
    );
}
