// components/nav/navbar.vue
<template>
    <nav class="bg-transparent p-4 fixed top-0 right-0 w-full">
        <div class="container mx-auto flex justify-end items-center space-x-4">
            <div class="relative group">
                <a href="https://blog.mooshieblob.com" class="text-white hover:text-gray-400 hover:text-xl hover:font-bold transition duration-300">
                    Blog
                </a>
            </div>
            <div class="relative group">
                <a href="https://comfy.mooshieblob.com" class="text-white hover:text-gray-400 hover:text-xl hover:font-bold transition duration-300">
                    ComfyUI
                </a>
            </div>
            <div class="relative group">
                <nuxt-link to="/images" class="text-white hover:text-gray-400 hover:text-xl hover:font-bold transition duration-300">
                    Images
                </nuxt-link>
            </div>
        </div>
    </nav>
</template>

<script>
import '~/assets/css/output.css';

export default {
    name: 'Navbar'
}
</script>

<style>
/* Add any additional styles here if needed */
</style>

// components/nav/Navbar.tsx
import type { JSX } from "preact/jsx-runtime";

export default function Navbar(): JSX.Element {
	return (
		<nav class="fixed right-0 top-0 w-full bg-transparent p-4">
			<div class="container mx-auto flex items-center justify-end space-x-4">
				<div class="group relative">
					<a
						href="/blog"
						class="hover:glow text-white transition duration-700 hover:text-yellow-400"
					>
						Blog
					</a>
				</div>
				<div class="group relative">
					<a
						href="https://comfy.mooshieblob.com"
						class="hover:glow text-white transition duration-700 hover:text-yellow-400"
					>
						ComfyUI
					</a>
				</div>
				<div class="group relative">
					<a
						href="/images"
						class="hover:glow text-white transition duration-700 hover:text-yellow-400"
					>
						Images
					</a>
				</div>
			</div>
		</nav>
	);
}
